/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A project in Arthropod, comprising a list of tasks
 */
export type ProjectDocV2 = ProjectDocV1 & {
  description: string
}

/**
 * A project in Arthropod, comprising a list of tasks
 */
export interface ProjectDocV1 {
  title: string
  /**
   * A list of tasks in the project
   */
  tasks: ProjectDocTask[]
  authorIds?: string[]
}
/**
 * A distinct thing to do in a project
 */
export interface ProjectDocTask {
  id: string
  title: string
  description: string
  complete: boolean
}
